language: java
sudo: false
script: mvn clean verify
jdk: oraclejdk8

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # MySQL setup
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'
  - mysql -u root test < sql/db.sql